server:
  port: 9099

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC

  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.wym: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.wym.*.entity